#===================================================================+
#    ____                            __                  _          |
#   / __ \   _____  ____   _   __   /_/  ____   _____   (_)  ____ _ |
#  / /_/ /  / ___/ / __ \ | | / /  / /  / __ \ / ___/  / /  / __ `/ |
# / ____/  / /    / /_/ / | |/ /  / /  / / / // /__   / /  / /_/ /  |
#/_/      /_/     \____/  |___/  /_/  /_/ /_/ \___/  /_/   \__,_/   |
#                                                                   |
#===================================================================+

npcs:
  '7': iniciador
  '0': stan
  '1': livia
  '14': teleportador
  '11': gizelo_binto
  
hide_npcs:
  10: "!matarBandidoMelee"
  9: "!matarBandidoRanged"