#===================================================================+
#    ____                            __                  _          |
#   / __ \   _____  ____   _   __   /_/  ____   _____   (_)  ____ _ |
#  / /_/ /  / ___/ / __ \ | | / /  / /  / __ \ / ___/  / /  / __ `/ |
# / ____/  / /    / /_/ / | |/ /  / /  / / / // /__   / /  / /_/ /  |
#/_/      /_/     \____/  |___/  /_/  /_/ /_/ \___/  /_/   \__,_/   |
#                                                                   |
#===================================================================+

npcs:
  '23': lixosvaldo
  
hide_npcs:
  24: "!lixo1,!cidadeSuja"
  25: "!lixo2,!cidadeSuja"
  26: "!lixo3,!cidadeSuja"
  27: "!lixo4,!cidadeSuja"
  28: "!lixo5,!cidadeSuja"
  29: "!lixo6,!cidadeSuja"
  30: "!lixo7,!cidadeSuja"
  31: "!lixo8,!cidadeSuja"
  32: "!lixo9,!cidadeSuja"
  33: "!lixo10,!cidadeSuja"
  34: "!lixo11,!cidadeSuja"
  35: "!lixo12,!cidadeSuja"
  36: "!lixo13,!cidadeSuja"
  37: "!lixo14,!cidadeSuja"
  38: "!lixo15,!cidadeSuja"
  39: "!lixo16,!cidadeSuja"